# Generated by Django 4.1.5 on 2023-03-25 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Employee_Name', models.TextField(max_length=200)),
                ('Employee_Age', models.IntegerField()),
                ('Employee_Sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=200)),
                ('Employee_JDate', models.DateField(auto_now_add=True)),
                ('Employee_Salary', models.DecimalField(decimal_places=2, max_digits=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=500)),
                ('Project_Start_Date', models.DateField(auto_now_add=True)),
                ('Project_End_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Department_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Department_Name', models.CharField(max_length=200)),
                ('Department_Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.employee')),
                ('Department_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.project')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CEO', models.CharField(max_length=500)),
                ('Name', models.CharField(max_length=500)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.department')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.project')),
            ],
        ),
    ]
