# Generated by Django 4.1.5 on 2023-03-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Employee_Email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
